config/routes.rb
HcfIo::Application.routes.draw do
  resources :sessions
  resources :users

  get "projects/default"

  resources :projects do
    resources :files,
              :controller => "source_files",
              :constraints => { :id => /[^\/]+(?=\.html\z|\.json\z)|[^\/]+/ }
  end

  get "home/index"
  root :to => "home#index"
  post "/login" => "sessions#login"
  get "/logout" => "sessions#logout"

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :source_files
  belongs_to :user
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/source_file.rb
class SourceFile < ActiveRecord::Base
  belongs_to :project
end

app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  has_many :projects

  validates_length_of :login, :within => 3..40
  validates_length_of :password, :within => 5..40
  validates_presence_of :login, :email, :password, :password_confirmation, :pw_salt
  validates_uniqueness_of :login, :email
  validates_confirmation_of :password
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, :message => "invalid email format"

  attr_protected :id, :pw_salt
  attr_accessor :password, :password_confirmation


  def self.authenticate(login, pass)
    u = find(:first, :conditions=>["login = ?", login])
    u = u || find(:first, :conditions=>["email = ?", login])
    return nil if u.nil?
    return u if User.encrypt(pass, u.pw_salt) == u.pw_hash
    nil
  end

  def password=(pass)
    @password=pass
    self.pw_salt = User.random_string(10) if !self.pw_salt?
    self.pw_hash = User.encrypt(@password, self.pw_salt)
  end

  def send_new_password
    new_pass = User.random_string 10
    self.password = self.password_confirmation = new_pass
    self.save
    #Notifications.deliver_forgot_password(self.email, self.login, new_pass)
  end

  protected

  def self.encrypt(pass, salt)
    Digest::SHA1.hexdigest(pass.to_s+salt.to_s)
  end

  def self.random_string(len)
    # generate a random string consisting of strings and digits
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    newpass = ""
    1.upto(len) { |_| newpass << chars[rand(chars.size-1)] }
    return newpass
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :setup_login_form

  def setup_login_form
    if session[:user] == nil
      puts "Woot"
      @user = User.new
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to "/projects/default"
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json {
        render json: {:project => @project, :files => @project.source_files}
      }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @user = session[:user]
    p "user"
    p @user
    @user.projects.create(params[:project])

    respond_to do |format|
      if @project.save
        @project.source_files.create :name=>"entry.s"
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end

  def default
    redirect_to Project.find(1)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    if request.post?
      p params
      if session[:user] = User.authenticate(params[:login], params[:password])
        p "good" 
        flash[:message]  = "Login successful"
        redirect_to params[:src]
      else
        p "bad"
        redirect_to params[:src]
      end
    end
  end

  def logout
    session[:user] = nil
    redirect_to "/"
  end
end

app/controllers/source_files_controller.rb
class SourceFilesController < ApplicationController

  # GET /projects/:id/source_files/:file_name
  # GET /projects/:id/source_files/:file_name.json
  def index
    
  end

  # POST /projects/1/files
  # POST /projects/1/files.json
  def create
    @project = Project.find params[:project_id]
    @file = @project.source_files.create :name=>params[:name], :code=>params[:code]

    respond_to do |format|
      if @file.save 
        format.html {redirect_to @project}
        format.json {render json: @file}
      end
    end
  end

  def show
    @project = Project.find params[:project_id]
    @file = @project.source_files.find_by_name params[:id]
  
    respond_to do |format|
      format.html 
      format.json {render json: @file}
    end
  end

  def update
    @user = session[:user]
    @project = Project.find params[:project_id]
    @file = @project.source_files.find_by_name params[:id]

    @file.code = params[:code]
    respond_to do |format|
      if @file.save
        p "\nok\n"
        format.html { redirect_to @file }
        format.json { head :ok }
      else
        p "\nerror\n"
        format.html { render action: "edit" }
        format.json { render json: @file.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find_by_login(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    #@user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user] = @user
        format.html { redirect_to params[:src], notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
     else
        format.html { redirect_to params[:src], notice: 'Error' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/2.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/source_files_helper.rb
module SourceFilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">hcf.io alpha</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#emulator" data-toggle="tab">Emulator</a></li>
          <li><a href="#disassembler" data-toggle="tab">Disassembler</a></li>
          <li><a href="#font-editor" data-toggle="tab">Font Editor</a></li>
          <li><a href="#about" data-toggle="tab">About</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <div class="well sidebar-nav">
        <ul id="projFiles" class="nav nav-list">
          <li class="nav-header">Project Files</li>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div class="span10">
      <div class="tab-content">
        <div id="emulator" class="tab-pane active">
          <div class="row-fluid">
            <div class="span5">
              <ul id="openFiles" class="nav nav-tabs">
                <li><a href="#newFile" data-toggle="modal"><i class="icon-plus"></i></a></li>
              </ul>
              <div id="openFileContents" class="tab-content">
              </div><!--tab-contents-->
            </div><!--span-->
            <div class="span5">
              <br>
              <br>
              <canvas id="framebuffer" width="544" height="448">
                Sorry, you need a HTML5 browser to use the LEM1802
              </canvas>
              <br>
              <span>
                <button id="btnRun" class="btn"><i class="icon-play"></i>Run</button>
                <button id="btnStep" class="btn"><i class="icon-step-forward"></i>Step</button>
                <button id="btnReset" class="btn"><i class="icon-refresh"></i>Reset</button>
                <button id="btnAssemble" class="btn">Assemble</button>
                <span class="pull-right" style="margin-right: 100">
                  Cycles: <span id="cycles">0</span>
                </span>
              </span>
            </div><!--span-->
          </div>
          <br>
          <div class="row-fluid">
            <div class="span4">
              <table class="table mono" style="margin-top: 18px;">
              <thead>
                <tr>
                  <th colspan="4">Registers</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>A: </td>
                  <td id="RegA" class="reg mono">0x0000</td>
                  <td>B: </td>
                  <td id="RegB" class="reg mono">0x0000</td>
                  <td>C: </td>
                  <td id="RegC" class="reg mono">0x0000</td>
                </tr>
                <tr>
                  <td>X: </td>
                  <td id="RegX" class="reg mono">0x0000</td>
                  <td>Y: </td>
                  <td id="RegY" class="reg mono">0x0000</td>
                  <td>Z: </td>
                  <td id="RegZ" class="reg mono">0x0000</td>
                </tr>
                <tr>
                  <td>I: </td>
                  <td id="RegI" class="reg mono">0x0000</td>
                  <td>J: </td>
                  <td id="RegJ" class="reg mono">0x0000</td>
                  <td></td>
                  <td></td>
                </tr>
                <tr>
                  <td>PC: </td>
                  <td id="RegPC" class="reg mono">0x0000</td>
                  <td>SP: </td>
                  <td id="RegSP" class="reg mono">0xffff</td>
                  <td>EX: </td>
                  <td id="RegEX" class="reg mono">0x0000</td>
                </tr>
              </tbody>
              </table>
            </div>
            <div class="span6">
              <table class="table mono">                                                                                                                                          
              <thead>                                                                                                                                                             
                <tr>                                                                                                                                                                
                  <th colspan="2">Memory Dump</th>                                                                                                                                  
                  <th></th>                                                                                                                                                         
                  <th>Base:</th>                                                                                                                                                    
                 <th colspan="5"><input id="membase" type="text" value="0x0"/>                                                                                                     
                </tr>                                                                                                                                                                
                <tr>                                                                                                                                                                
                  <th>Addr</th>                                                                                                                                                     
                  <th>0000</th>                                                                                                                                                     
                  <th>0001</th>                                                                                                                                                     
                  <th>0002</th>                                                                                                                                                     
                  <th>0003</th>                                                                                                                                                     
                  <th>0004</th>                                                                                                                                                     
                  <th>0005</th>                                                                                                                                                     
                  <th>0006</th>                                                                                                                                                     
                  <th>0007</th>                                                                                                                                                     
                </tr>                                                                                                                                                               
                </thead>                                                                                                                                                            
                <tbody id="memdump-body">                                                                                                                                           
              </tbody>                                                                                                                                                            
              </table> 
            </div>
          </div>
        </div><!--/tab-pane-->
        <div id="disassembler" class="tab-pane">
          <h3>Disassembler</h3>
          <p>Under Construction</p>
        </div><!--/tab-pane-->
        <div id="font-editor" class="tab-pane">
          <h3>Font Editor</h3>
          <p>Under Construction</p>
        </div>
        <div id="about" class="tab-pane">
          <h3>About</h3>
          <p>Under Construction</p>
        </div><!--/about-tab-->
      </div> <!--/tab-content-->
    </div> <!--/span-->
  </div><!--/row-->
  <hr>
  <!--
  <footer>
    <p>&copy; Company 2012</p>
  </footer>
  -->
</div><!--/.fluid-container-->

<div class="modal" id="newFile">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">×</button>
    <h3>Create File</h3>
  </div>
  <div class="modal-body">
    <form>
      Filname: <input id="inNewfn" type="text"></input>
    </form>
  </div>
  <div class="modal-footer">
    <button class="btn" onClick="$('#newFile').modal('toggle')">
      Close
    </button>
    <button class="btn btn-primary" onClick="app.create($('#inNewfn').val())">
      Create
    </button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>hcf.io |</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="icon" type="image/png" href="/favicon.png">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">hcf.io alpha</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="#emulator" data-toggle="tab">Emulator</a></li>
          <li><a href="#disassembler" data-toggle="tab">Disassembler</a></li>
          <li><a href="#font-editor" data-toggle="tab">Font Editor</a></li>
          <li><a href="#about" data-toggle="tab">About</a></li>
        </ul>
        <% if not session[:user] %>
          <a href="#loginModal" class="btn pull-right" data-toggle="modal">
            Login
          </a>
        <% else %>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i>
              <%= session[:user].email %>
            </a>
            <ul class="dropdown-menu">
              <li><a href="#">Settings</a></li>
              <li class="divider"></li>
              <li><a href="/logout">Logout</a></li>
            <ul>
          </div>
        <% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

<%= yield %>

<footer>
  <hr>
  <p>&copy; Tim Detwiler 2012</p>
</footer>

<% if not session[:user] %>
<div id="loginModal" class="modal fade">
  <div class="tab-content">


    <div id="login" class="tab-pane active">
    <form action="/login" method="post">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h6>Login</h6>
      </div>
      <div class="modal-body">
        <%= label_tag "Username or Email" %>
        <%= text_field_tag "login" %>

        <%= label_tag "Password" %>
        <%= password_field_tag "password" %>

        <%= hidden_field_tag "src", request.url %>
      </div>
      <div class="modal-footer">
        <a class="pull-left" href="#signup" data-toggle="tab">Don't have an accout? Sign Up.</a>
        <button type="submit" class="btn btn-primary">Login</a>
      </div>
    </form>
    </div>


    <div id="signup" class="tab-pane">
    <%= form_for @user do |f| %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h6>Sign Up</h6>
      </div>
      <div class="modal-body">
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
        <%= f.label :login %><br />
        <%= f.text_field :login %>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
        <%= hidden_field_tag "src", request.url %>
      </div>
      <div class="modal-footer">
        <a class="pull-left" href="#login" data-toggle="tab">Already have an account? Login.</a>
        <%= f.submit "Sign Up", :class=>"btn btn-primary" %>
      </div>
    <% end %>
    </div>
<% end %>


  </div>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to 'Show', project %></td>
    <td><%= link_to 'Edit', edit_project_path(project) %></td>
    <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/source_files/index.html.erb
<h1>fuck you noughth</h1>

app/views/source_files/show.html.erb
<h1>File <%= @file.name %></h1>

<pre>
<%= @file.code %>
</pre>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Pw hash</th>
    <th>Pw salt</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.pw_hash %></td>
    <td><%= user.pw_salt %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
  <h1>New user</h1>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>